# -*- coding: utf-8 -*-
"""programacion uni

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjhRUWvyOzje4Nat6ZPdQ-wKqC8JKSrg
"""



"""# corte 1
Lección 1-Fundamentos de python
"""

print("hola mundo")

nombre=input("¿cual es tu nombre?")
print("hola mundo de",nombre)

nombre="jesus"
edad=19
altura=1.76
soltero=True

print("tipos de dato:")
print(type(nombre))
print (type(soltero))
print(type(altura))
print(type(edad))

print("hola", nombre, "tienes", edad-10)

"""Clase 2 (24/08/2026)

"""

#operaciones matematicas

vab1=20
vab2=15

print(vab1 + vab2)

print("La suma es:",vab1 + vab2)

vab1 = 20
vab2 = 15
suma= vab1 + vab2

print(vab1,"+",vab2,"=", suma)

vab1 = 20
vab2 = 15

suma= vab1 + vab2
resta= vab1 - vab2
multiplicacion= vab1 * vab2
division= vab1 / vab2

print (vab1,"+",vab2,"=",suma)
print (vab1,"-",vab2,"=",resta)
print (vab1,"*",vab2,"=",multiplicacion)
print (vab1,"/",vab2,"=",division)

nombre = input("Indicanos tu nombre: ")

print("por favor indicame 3 notas para calcular el promedio")

nota1 = float(input("nota 1: "))
nota2 = float(input("nota 2: "))
nota3 = float(input("nota 3: "))
suma = (nota1+nota2+nota3)
promedio=suma/3
print("suma de notas", suma)
print("El promedio de notas es", promedio)

"""Ejercicio 1-cafeteria universitaria"""

print("BIENVENIDO A LA TIENDA UNIVERSITARIA")
cantidad_productos = int(input("ingresa la cantidad de productos comprados?"))
precio_unitario = float(input("precio unitario de cada producto"))
subtotal = cantidad_productos * precio_unitario
print("El subtotal es",subtotal)
descuento = subtotal * 0.10
print("El descuento es", descuento)
total_a_pagar_sin_IVA = subtotal - descuento
print("El total a pagar sin IVA es:", total_a_pagar_sin_IVA)
vab1IVA = 19 / 100
costoIVA = vab1IVA * subtotal
print("Costo del IVA 19%:", costoIVA)
total_final= total_a_pagar_sin_IVA + costoIVA
print("el total final es:",total_final)

"""Ejercicio 2-viaje en automovil"""

distancia = float(input("Ingresa la distancia del viaje (km): "))
rendimiento = float(input("Ingresa el rendimiento del automóvil (km/L): "))
precio_gasolina = float(input("Ingresa el precio de un litro de gasolina ($/L): "))
litros_de_gasolina_necesarios_para_realizar_el_viaje = distancia / rendimiento
print("La cantidad de gasolina necesaria para el viaje es:",
      litros_de_gasolina_necesarios_para_realizar_el_viaje, "L")
precio_total_del_combustible = precio_gasolina * litros_de_gasolina_necesarios_para_realizar_el_viaje
print("El costo total de la gasolina es:",
      precio_total_del_combustible, "$")
costo_combustible_aumentando = precio_total_del_combustible * 1.08
print("El costo del combustible aumentando 8% es:",
      costo_combustible_aumentando, "$")
costo_dividiendo_entre_3 = precio_total_del_combustible / 3
print("El costo dividido entre 3 personas es:",
      costo_dividiendo_entre_3, "$ por persona")
costo_total_del_viaje_ida_y_vuelta = precio_total_del_combustible * 2
print("El costo total del viaje de ida y vuelta es:",
      costo_total_del_viaje_ida_y_vuelta, "$")

"""Clase 07/09-Ciclos for y while"""

num1 = int(input("dame un numero: "))
num2 = int(input("dame otro numero: "))
num3 = int(input("dame otro numero: "))
suma = num1+num2+num3
print("La suma es: ", suma)

cuantosnumerossumar = int(input("¿cuantos numeros deseas sumar?"))

acumuladosuma = 0

for i in range(cuantosnumerossumar):
  numero = int(input("dame el numero que quieres sumar"))
  acumuladosuma = acumuladosuma + numero

print("la suma es", acumuladosuma)

for i in range(5):
  print("i=", i)

for i in range(3):
  print("esta por dentro del bucle: ", i, "vez")
print("esta por fuera")

#caso 1
print("#caso 1")
for i in range(5):
  print("i=", i)

  #caso 2
print("#caso 2")
for i in range(1,5):
   print("i=", i)

  #caso 3
print("#caso 3")
for i in range(1,5,2):
    print("i=", i)

notas = [3.5, 4.2, 2.8, 5.0]
for nota in notas:
  print ("La nota es:", nota)

notas = [3.5, 4.2, 2.8, 5.0]
suma = 0
for nota in notas:
  suma = suma + nota
print("promedio:", suma / len(notas))

n = 5
while n > 0:
  print(n)
  n = n - 1
print("!despegue!")

edad = int(input("tu edad:"))

while edad <= 0 or edad >50:
  print("eso no es valido")
  edad = int(input("tu edad: "))

"""Ejercicios de practica"""

for i in range (1,21):
  print("i=",i)

multiplicacion = [7*1, 7*2, 7*3, 7*4, 7*5, 7*6, 7*7, 7*8, 7*9, 7*10,]
multiplicaciones = 0
for i in multiplicacion:
  multiplicacion = multiplicaciones * multiplicacion
  print("i=",i)

precios = [1200, 3500, 800]

total = 0

for precio in precios:
   total = total + precio

print(total)

edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no válida")
elif edad <= 12:
    print("Niño")
elif edad <= 17:
    print("Adolescente")
elif edad <= 59:
    print("Adulto")
else:
    print("Adulto mayor")

nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")
elif nota >= 3.0:
    print("Aprobó")

elif nota >= 2.5:
  print("habilitacion")

else:
  print("reprobo")

rol = input("Ingrese su rol (estudiante/docente/administrador): ")

if rol == "estudiante":
    print("Bienvenido/a estudiante")

elif rol == "docente":
  print("Bienvenido/a docente")

elif rol == "administrador":
  print("Bienvenido/a administrador")

peso = float(input("Ingrese su peso en kg: "))
estatura = float(input("Ingrese su estatura en metros: "))
imc = peso / (estatura ** 2)

if imc < 18.5:
    print("Bajo peso")

elif imc < 18.5:
  print("peso normal")

elif imc < 25.0:
  print("sobrepeso")

else:
  print("obesidad")

compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ")
es_estudiante = respuesta == "si"

descuento = 0.0
if es_estudiante:
    descuento += 0.15

"""ESTRUCTURAS DE DATOS - 28/09/2026"""

listaNumeros = [2, 3.5, 4, 100]
numero = 5

listaNumeros[3] = 80

print(type(listaNumeros))
print("tamaño lista ->",len(listaNumeros))

print(listaNumeros)
print("Los valores en la lista son: ")
i=0
for valor in listaNumeros:
  print("listaNumeros[",i, "] =",valor)
  i+=1

listafrutas = ["manzana", "pera" , "fresa"]
print(listafrutas)

listafrutas[1]="mango"
print(listafrutas)

listadatospersonales = ["jesus gonzalez", 19, 1.78, "jesusgonzalez17123@gmail.com", "cra 2 22 222", "barrio imaginario"]
print(listadatospersonales)

print("FORMULARIO GENERICO")
nombre=input("indicame tu nombre:")
edad= int(input("La edad:"))
altura= float (input("Dame tu altura:"))
correo=input("indicame tu correo:")
direccion=input("indicame tu direccion:")
barrio=input("indicame tu barrio:")

listausario = [ nombre , edad , altura , correo , direccion , barrio]
print(listausario)

grupoclase = [listausario, listausario, listausario, listausario]
print(grupoclase)

"""clase 05/10 listas

"""

pedido = ["laura gomez , 3 , 45500.0 , false , calle 45 #12-30"]
print("nombre cliente:",pedido[0])
print("direccion:", pedido[-1])